<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TKG3d\TKG3d.csproj" />
    <ProjectReference Include="..\TKGeomBase\TKGeomBase.csproj" />
  </ItemGroup>

</Project>
